### ISSUE TITLE
SPRINT 4 - Ruth: Análise exploratória dos dados das KPIs e tratamento dos dados

### ISSUE THREAD

**Issue by GABRIELalmeida0** [GABRIELalmeida0/Projeto-integrador-Servi-o-de-Monitoramento-de-KPI-de-Rede#12]

**Comment by F3L1CITY** [comment]
As métricas passaram dias sendo recolhidas na aplicação.

**Comment by F3L1CITY** [comment]
Enquanto os dados foram capturados, eu pude fazer a análise dos dados das KPIs.

**Comment by F3L1CITY** [comment]
Com os dados e as análises o tratamento dos dados pode começar a ser feito. Quanto mais as métricas são obtidas, mais posso chegar a melhores decisões de quais métricas são ideais para o estudo.
